# Site settings
title: Hack your own software projects using cloud hosting
email: cr0hn[at]cr0hn.com
author: Daniel Garcia (cr0hn)
project_name: idsFree
project_site: http://idsfree.github.io
download_url: https://github.com/BBVA/idsfree
short_description: >
  <p>Hack your own software projects using cloud host providers<p>
  <h2 style="color:#F88C30"><b>Safe</b> - <b>Isolated</b> - <b>Easy</b> - <b>Useful</b></h2>
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: ggdaniel
github_username:  cr0hn

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      body_color: "orange"
      layout: "page"
      title_icon: fa fa-link

# allowed colors: green, blue, orange, red, pink, purple
